# Selección del lenguaje, en nuestro caso python. 
language: python   

python:
  - "2.7" 

install:   # Instalación de dependencias
  - sudo apt-get install libmysqlclient-dev
  - sudo apt-get install python-dev
  - pip install --upgrade pip
  - pip install MySQL-python
  - pip install Django 
  - pip install nose  

script:       # El script que ejecutaremos para que nuestro código funcione y corra los test.
  - make test

branches:     # decidimos que TravisCI solo compruebe los test del master de github.
  - only:
    - master

notifications:   # Notificamos los resultados de los test por correo
  recipients:
    - rubenmartin1991@gmail.com
  email:
    on_success: change
    on_failure: always

