---
- hosts: AzureDB
  sudo: yes
  remote_user: pluco
  tasks:
  - name: Actualizar sistema base
    apt: update_cache=yes upgrade=dist 
  - name: Instalar paquetes necesarios
    apt: name=mysql-server state=installed
    apt: name=mysql-client state=installed
    apt: name=git state=installed
    apt: name=make state=installed
  - name: Clonar repositorio desde git
    git: repo=https://github.com/romilgildo/IV-PLUCO-RMH.git dest=IV-PLUCO-RMH clone=yes force=yes
  - name: Configurar MySQL
    shell: cd IV-PLUCO-RMH/mysql && cp my.cnf /etc/mysql/
    shell: cd IV-PLUCO-RMH/mysql && cp hosts.allow /etc/
  - name: Instalar requisitos para la BD
    shell: cd IV-PLUCO-RMH && make install
  - name: Sincronizar base de datos
    command: chdir=IV-PLUCO-RMH python manage.py syncdb
