---
- hosts: localhost
  sudo: yes
  remote_user: pluco
  tasks:
  - name: Actualizar sistema base
    apt: update_cache=yes upgrade=dist 
  - name: Instalar paquetes necesarios
    action: apt pkg={{ item }} state=installed
    with_items:
      - mysql-server
      - git
      - make
  - name: Clonar repositorio desde git
    git: repo=https://github.com/romilgildo/IV-PLUCO-RMH.git dest=IV-PLUCO-RMH clone=yes force=yes
  - name: Configurar fichero my.cnf
    shell: cd IV-PLUCO-RMH/despliegueMySQL && sudo cp my.cnf /etc/mysql/
  - name: Configurar fichero hosts.allow
    shell: cd IV-PLUCO-RMH/despliegueMySQL && sudo cp hosts.allow /etc/
  - name: Matar proceso mysqld
    shell: sudo killall mysqld
  - name: Reiniciar servidor mysql
    shell: sudo /etc/init.d/mysql restart
  - name: Crear usuario admin
    shell: cd IV-PLUCO-RMH/despliegueMySQL && mysql -u root < usuarioMySQL
  - name: Instalar requisitos para la BD
    shell: cd IV-PLUCO-RMH && make install
  - name: Preparar modelos base de datos
    shell: cd IV-PLUCO-RMH && python manage.py makemigrations plucoapp
  - name: Crear tablas base de datos
    shell: cd IV-PLUCO-RMH && python manage.py migrate
