VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.env.enable # para variables de entorno

  config.vm.box = 'azure'
  config.vm.network "public_network"
  config.vm.define "localhost" do |l|
	l.vm.hostname = "localhost"
  end

  config.vm.provider :azure do |azure, override|
    azure.mgmt_certificate = File.expand_path(ENV['AZURE_PEM'])
    azure.mgmt_endpoint = 'https://management.core.windows.net'
    azure.subscription_id = ENV['SUBSCRIPTION_ID']
    azure.vm_image = 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20151218-en-us-30GB'
    azure.vm_name = ENV['VM_MYSQL_NAME']
    azure.vm_user = ENV['VM_USER']
    azure.vm_password = ENV['VM_PASS']
    azure.vm_location = 'Central US'
    azure.cloud_service_name = ENV['VM_MYSQL_NAME']
    azure.ssh_port = '22'
    azure.tcp_endpoints = '3306:3306'
  end

  config.ssh.username = ENV['VM_USER']
  config.ssh.password = ENV['VM_PASS']

  config.vm.provision "ansible" do |ansible|
	ansible.sudo = true
    ansible.playbook = "crearMySQL.yml"
	ansible.verbose = "v"
	ansible.host_key_checking = false
  end
end
